### ISSUE TITLE
HTTP 500 Error accessing getCOA method only

### ISSUE THREAD

**Issue by brettm-pmsa** [TheAlphaSchoolSystemPTYLTD/general-ledger-analytics#9]
Hi,

We are getting the below error when accessing the getCOA method:

Server Error
500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.
{"__status":"invalid","__forms":{"date":{"required":true,"options":"","type":"date"}},"__msg":"Element I50 is undefined in a CFML structure referenced as part of an expression.","__invalid":{},"__locks":{}}

Every other method works fine, no errors.  To generate the request URL I used the TASS PowerShell script and the only items I changed between the other calls to other methods that work and this getCOA method is the Method and the parameter.

In addition, we have 4 schools in our group that we are accessing their respective TASS APIs, and the other 3 schools all return data for this method fine - it is something unique to just this method at just that one school.

The only difference we can see is that the one school with issues is running a later version of TASS to the others - they have already updated to V59.03.200 General Release - 01.059.03.200 ( CF2021 , #23 ).

Any advice on how we can chase this down?

Thanks!
Brett.

**Comment by NerdGitJock** [comment]
reference CS-233453

**Comment by scottetass** [comment]
Hi Brett,

Did this get sorted after Customer Support contacted you? I want to make sure everything is OK before closing this issue.

Thanks, Scott

**Comment by brettm-pmsa** [comment]
Hi Scott,

Thanks for checking - unfortunately I don't know yet - they advised that we need to update reporting codes but our staff haven't had a chance yet to go through and do that for every entry.

Happy for you to close off this case though - I am pretty confident fixing the reporting codes will fix this issue.

Kind Regards,

Brett.


Brett Mildwaters  | Chief Information Officer
***@***.*** 
     
​    
​    
Presbyterian and Methodist Schools Association
07 3180 9110 | 0418 285 204
P O Box 298, Toowong, Queensland 4066 Australia
www.pmsa-schools.edu.au
The PMSA Group acknowledges the Traditional Custodians of the land on which our PMSA Group Office and schools now stand and where our students have the privilege of learning each day – the Turrbal peoples from the north side of the Brisbane River, the Jagera peoples from the south side of the Brisbane River and the Kabi Kabi and Jinibara peoples of the Sunshine Coast. We pay our respects to Elders past, present and emerging.
Confidential Notice: This message contains confidential information intended for a specific individual and purpose and is as such private. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or action based on the contents of this information is strictly prohibited. If you have received this message in error, please notify the sender and delete the message and any attachments immediately. The responsibility for virus detection is the recipients and we do not accept any responsibility for any loss or damage arising in any way from the use of this email or any attachments. Our Privacy Policy deals with how we collect, use and disclose personal information. If you would like to view our Privacy Policy, please request a copy by return email.
